name: Migrain Canary Build
on: 
  push:
    branches:
      - master

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    name: Build All OS
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.x'

    - name: Build Windows 64-bit
      run: dotnet publish -r win-x64 -c Release -o ./build/win64

    - name: Pack Windows 64-bit Build
      run: 7z a ./build/migrain_windows-x64.zip ./build/win64/*

    - name: Build OSX 10.12 64-bit
      run: dotnet publish -r osx-x64 -c Release -o ./build/osx64

    - name: Pack OSX 10.12 64-bit Build
      run: 7z a ./build/migrain_osx-x64.zip ./build/osx64/*

    - name: Build Linux 64-bit
      run: dotnet publish -r linux-x64 -c Release -o ./build/linux64
        
    - name: Pack Linux 64-bit Build
      run: 7z a ./build/migrain_linux-x64.zip ./build/linux64/*
       
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "canary"
        prerelease: true
        title: "Canary Build"
        files: build/*.zip
